#!/usr/bin/env bash
# Run this from the root directory

cd ./test || exit
source approvals.bash
PATH="$PATH:../"

# Update me
cli=download

# Tests (context and describe are optional)
context "when DEBUG is on"
  export DEBUG=1

  describe "root command"
    # for commands that fail (like without parameters), we add || 0
    approve "$cli" || 0
    approve "$cli --help"

context "when DEBUG is off"
  unset DEBUG

  describe "some other command"
    approve "$cli other" || 0
    approve "$cli other --help"

# ...more tests...